### ISSUE TITLE
misspelled node name

### ISSUE THREAD

**Issue by juanea** [nr-parikh/rosserial_tutorials#10]
There is a node name that is misspelled.
ros_arduino_muliple_pub_sub
instead of 
ros_arduino_multiple_pub_sub
It took me a while to found the issue why the first example was not running as it should.

Best Regards,
![screenshot from 2018-06-15 13-49-11](https://user-images.githubusercontent.com/9869942/41486908-958fd21e-70a3-11e8-8ee0-b4a3a943a17f.png)

**Comment by nr-parikh** [comment]
Thanks for the catch. I just fixed the mistake!
